In [ ]:
import numpy as np

a = np.ndarry (shape = (2, 2) , dtype=int)
a

array([[  643610302, -1623187696],
       [-1081286598,  1504689103]])

In [3]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int32


In [6]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
4
12


In [7]:
a.data

In [8]:
import numpy as np

np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [9]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [10]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [11]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [13]:
lang = np.array(['파이썬', '자바', '씨'], dtype=str)
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [14]:
a = np.array((1, 2, 3), dtype=float)
a

array([1., 2., 3.])

In [15]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

# w03-2

In [18]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [19]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [20]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [23]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
b = np.array([1, 2, 3, 4, 5, 6]). reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.reshape(b, (2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
import numpy as np

np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [29]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [30]:
print( (3-2) / (50-1) )

0.02040816326530612


In [31]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [32]:
print( (3-2) / 50 )

0.02


In [33]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [34]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [36]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [37]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [38]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [39]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

# w03-3

In [41]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [42]:
a.dtype

dtype('float64')

In [43]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [44]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [45]:
import numpy as np

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
import numpy as np

np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [49]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [51]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
a = np.eye(3, 4, -1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [53]:
import numpy as np

np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [54]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [59]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [58]:
import numpy as np

np.empty([2, 2])

array([[0.1, 0.2],
       [0.3, 0.4]])

In [60]:
np.empty(3)

array([0.1, 0.2, 0.3])

In [61]:
np.empty([2, 3], dtype=int)

array([[-1717986918,  1069128089, -1717986918],
       [ 1070176665,   858993460,  1070805811]])

In [62]:
import numpy as np

a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

# w03-4

In [66]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [67]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [68]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [71]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [72]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [73]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [74]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [76]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [77]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [78]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [79]:
a @ b

array([[12,  6],
       [12,  6]])

In [80]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [81]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [82]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [83]:
a.sum()

46

In [84]:
a.sum(axis=0)

array([16, 30])

In [85]:
a.sum(axis=1)

array([30, 13,  3])

In [87]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [88]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [89]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [90]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [91]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [92]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [93]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [94]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [95]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [96]:
np.add(a, b)

array([ 3,  6, 11])

In [97]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [98]:
np.power(a, b)

array([ 1, 16, 81])

# w03-5

In [100]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [101]:
print(a[3])
print(a[-2])

9
64


In [102]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [103]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [104]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

In [105]:
a[::-2]

array([81, 49, 25,  9,  1], dtype=int32)

In [106]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81],
      dtype=int32)

In [107]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81], dtype=int32)

In [108]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [109]:
b = np.array([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [110]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [111]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [112]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [113]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [114]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [115]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [116]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [117]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [118]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [119]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [120]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [121]:
a[2, 4]

16

In [122]:
a[2][4]

16

In [123]:
a[1:3, 2:5] 

array([[ 8,  9, 10],
       [14, 15, 16]])

In [124]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [125]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [126]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [127]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [128]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [129]:
a[:, 1, 1]

array([ 5, 17])

In [130]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [131]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [132]:
a[1, ..., 1]

array([13, 17, 21])

In [133]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [136]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [139]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [140]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [141]:
np.transpose(a, (0, 1))

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [143]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [144]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [145]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [146]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [147]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [148]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [149]:
c.transpose((1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [150]:
np.transpose(c, (1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [151]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [152]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [153]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [154]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [155]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [157]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [158]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [159]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [160]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [161]:
org

array([  0,   1, 200,   3,   4])

In [162]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [163]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [164]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [165]:
org 

array([0, 1, 2, 3, 4])

In [166]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [167]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
y.base

array([0, 1, 2, 3, 4, 5])

In [169]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [170]:
c = z.copy()
print(c.base)

None


In [172]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [173]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [174]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [175]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [176]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [177]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
b = a
b is a

True

In [180]:
print(id(a))
print(id(b))

2994929629584
2994929629584


In [181]:
print(b.base)

None


In [182]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [183]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [184]:
print(id(a))
print(id(v))

2994929629584
2994930368208


In [185]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [186]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

# w03-6

In [187]:
from  numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])
a + b

array([11, 11, 11])

In [188]:
from numpy import array

a = array([3, 4, 5, 7])
b = array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [189]:
from numpy import array

a = array([3, 4, 5])
a

array([3, 4, 5])

In [190]:
b = 2
b

2

In [191]:
a + b

array([5, 6, 7])

In [192]:
from numpy import array

A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [193]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

In [194]:
from numpy import arange


x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [196]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [197]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [198]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [199]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [200]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [201]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [202]:
from numpy import arange


x = arange(1, 4)
x

array([1, 2, 3])

In [203]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [204]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [205]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [206]:
from numpy import arange


x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [207]:
y = arange(1, 3)
y

array([1, 2])

In [208]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [209]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [210]:
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [211]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [212]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [213]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [214]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [215]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [217]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

# w03-7

In [218]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [220]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [221]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [222]:
x[np.array(([5, 3, -4, 8]))]

array([5, 3, 6, 8])

In [223]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [224]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [225]:
x[0, 1]

1

In [226]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [227]:
x[[0], [1]]

array([1])

In [228]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [229]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [230]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [231]:
x[[1, 3], [2, 2]]

array([10, 26])

In [232]:
x[[1, 3], [3, 3]]

array([11, 27])

In [233]:
x[[1, 3], [3]]

array([11, 27])

In [234]:
from numpy import array

x[array([0, 2, 4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [235]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [236]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [237]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [238]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [239]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [241]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [242]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [243]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])